### ISSUE TITLE
[BUG]  PhyloSeq file not generated and  MicrobiomeAnalyst folder not generated 

### ISSUE THREAD

**Issue by najibveto** [quadram-institute-bioscience/dadaist2#23]
hello,
I am trying to the dadaist on my data, however i have the following error:
```
dadaist2  --max-loss 0.04 -i feed/ -o example-output3 -d refs/SILVA_SSU_r138_2019.RData -t 8 -m metadata.tsv --verbose --force
    ____            __      _      __ ___
   / __ \____ _____/ /___ _(_)____/ /|__ \
  / / / / __ `/ __  / __ `/ / ___/ __/_/ /
 / /_/ / /_/ / /_/ / /_/ / (__  ) /_/ __/
/_____/\__,_/\__,_/\__,_/_/____/\__/____/

1.3.0
[2024-10-17 11:13:41] Ready to log in /home/najibveto/example-output3/dadaist.log
[2024-10-17 11:13:41] dadaist2 1.3.0
[2024-10-17 11:13:41] DECIPHER Taxonomy database found: refs/SILVA_SSU_r138_2019.RData
Use of uninitialized value in concatenation (.) or string at /home/najibveto/micromamba/envs/dadaist/bin/dadaist2 line 535.
[2024-10-17 11:13:41] Parameter: taxonomy-type:
[2024-10-17 11:13:41] Parameter: taxonomy-db: skip
 * Input directory: feed/
 * Output directory: /home/najibveto/example-output3/
 * Metadata: metadata.tsv
 * Reference database: skip
 * Threads: 8
 * Temporary directory: /tmp/dadaist2_2c36TR
 * QC strategy: skip
[2024-10-17 11:13:41] QC: Checking quality profile with SeqFu
[2024-10-17 11:13:42] SeqFu quality truncation at (trunc-len-1 and trunc-len-2): 283 - 211
[2024-10-17 11:13:42] Checking dependencies
 * DECIPHER: <pass>
 * RScript: R scripting front-end version 4.0.5 (2021-03-31)
 * assign-taxonomy: dadaist2-assigntax 1.1.3
 * clustalo: 1.2.4
 * dada2 (lib): <pass>
 * exporter: dadaist2-exporter 1.4.0
 * fastp: fastp 0.23.4
 * fasttree: FastTree version 2.1.11 Double precision (No SSE3):
 * fu-primers: fu-primers 1.22.3
[2024-10-17 11:13:49] Temporary directory: /tmp/dadaist2_2c36TR
[2024-10-17 11:13:49] Threads: 8
[2024-10-17 11:13:49] Output directory: /home/najibveto/example-output3/
[2024-10-17 11:13:49] Checked metadata for C11
[2024-10-17 11:13:49] Checked metadata for C12
[2024-10-17 11:13:49] Checked metadata for C13
[2024-10-17 11:13:49] Checked metadata for C21
[2024-10-17 11:13:49] Checked metadata for C22
[2024-10-17 11:13:49] Checked metadata for C23
[2024-10-17 11:13:49] Input directory "feed/": 6 found (paired-end)
[2024-10-17 11:13:49] (1/6) Processing C11: skip
[2024-10-17 11:13:49] Copying input reads for DADA2
[2024-10-17 11:13:49] (2/6) Processing C12: skip
[2024-10-17 11:13:49] Copying input reads for DADA2
[2024-10-17 11:13:49] (3/6) Processing C13: skip
[2024-10-17 11:13:49] Copying input reads for DADA2
[2024-10-17 11:13:50] (4/6) Processing C21: skip
[2024-10-17 11:13:50] Copying input reads for DADA2
[2024-10-17 11:13:50] (5/6) Processing C22: skip
[2024-10-17 11:13:50] Copying input reads for DADA2
[2024-10-17 11:13:50] (6/6) Processing C23: skip
[2024-10-17 11:13:50] Copying input reads for DADA2
[2024-10-17 11:13:50] Running DADA2...
[2024-10-17 11:13:50] Dada2 script parameters:
 * [1] forward_reads: /tmp/dadaist2_2c36TR/for
 * [2] reverse_reads: /tmp/dadaist2_2c36TR/rev
 * [3] feature_table_output: /tmp/dadaist2_2c36TR/dada2/dada2.tsv
 * [4] stats_output: /tmp/dadaist2_2c36TR/dada2/stats.tsv
 * [5] filt_forward: /tmp/dadaist2_2c36TR/for/filtered
 * [6] filt_reverse: /tmp/dadaist2_2c36TR/rev/filtered
 * [7] truncLenF: 283
 * [8] truncLenR: 211
 * [9] trimLeftF: 0
 * [10] trimLeftR: 0
 * [11] maxEEF: 1
 * [12] maxEER: 1.5
 * [13] truncQ: 10
 * [14] chimeraMethod: consensus
 * [15] minFold: 1
 * [16] threads: 8
 * [17] nreads_learn: 0
 * [18] baseDir: /tmp/dadaist2_2c36TR
 * [19] doPlots: do_plots
 * [20] taxonomyDb: skip
 * [21] saveRDS: no
 * [22] noMerge: 0
 * [23] processPool: 0
[2024-10-17 11:21:36] DADA2 Finished.
[2024-10-17 11:21:36] 808 representative sequences found.
[2024-10-17 11:21:36] DADA2 filtered 8.1101% from total 890815 to 72246
[2024-10-17 11:21:36] Assigning taxonomy using DECIPHER: refs/SILVA_SSU_r138_2019.RData
[2024-10-17 11:29:24] Multiple sequence alignment and tree generation
[2024-10-17 11:30:08] Feature tree generated
[2024-10-17 11:30:08] MicrobiomeAnalyst not ready.
[2024-10-17 11:30:08] PhyloSeq file not generated: /home/najibveto/example-output3/R/phyloseq.rds
[2024-10-17 11:30:08] Diagnostics: ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ dadaist2-phyloseqMake 1.3.0                                                                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/home/najibveto/micromamba/envs/dadaist/bin/dadaist2-phyloseqMake", line 45, in <module>
    dadaistDir = dadaist2.DadaistOutputDir(args.input, verbose=args.verbose)
  File "/home/najibveto/micromamba/envs/dadaist/bin/dadaist2-console.py", line 51, in __init__
    self._check_sample_names()
  File "/home/najibveto/micromamba/envs/dadaist/bin/dadaist2-console.py", line 88, in _check_sample_names
    with open(os.path.join(self.path, "MicrobiomeAnalyst", "table.csv"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/najibveto/example-output3/MicrobiomeAnalyst/table.csv'
[2024-10-17 11:30:08] Rhea input files prepared, but normalization and alpha div. skipped.
[2024-10-17 11:30:08] Dadaist finished, output files saved:
 * decipher-taxonomy-table: /home/najibveto/example-output3/taxonomy.txt
 * feature-table: /home/najibveto/example-output3/feature-table.tsv
 * features-tree: /home/najibveto/example-output3/rep-seqs.tree
 * multiple-alignment: /home/najibveto/example-output3/rep-seqs.msa
 * rep-seqs: /home/najibveto/example-output3/rep-seqs.fasta

[2024-10-17 11:30:08] Cleaning up
```
how is it possible to fix it?
thank you for your help.

**Comment by telatin** [comment]
Hello @najibveto 
thanks for reporting this issue. The problem is upstream, as *MicrobiomeAnalyst not ready.*, I'll have a look and probably will need to ask you some more info later :)

Cheers

**Comment by najibveto** [comment]
@telatin 
thank you for your reply.
regards.

**Comment by telatin** [comment]
Hi there, I’m adding new format checks to catch failing conversions.
